global using RemoteControls.CoreLibrary.Helpers;
global using js = CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.JsonSerializers.NewtonJsonStrings;
global using Microsoft.AspNetCore.SignalR.Client;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.BasicExtensions;